name: BisphosphineConformerSelection
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11.7
  - matplotlib
  - numpy
  - mdanalysis
  - pandas
  - seaborn
  - morfeus-ml
  - tqdm
  - scikit-learn
  - openpyxl
  - scipy
  - pip:
    - autoelbow